### PR TITLE
[PHP/Symfony] Replace Apache2/CGI by NGINX/PHP-FPM

### PR DESCRIPTION
**Pull request by Alban-io**
Hello

To improve PHP benchmark performance I propose to replace :
- Apache2 -> Nginx 
- mod_php -> PHP-FPM (FastCGI) 

**Apache2  - mod_php** *(1344 requests   20/s)*
```
checks.........................: 100.00% 1344
data_received..................: 1.8 MB  27 kB/s
data_sent......................: 356 kB  5.3 kB/s
http_req_blocked...............: avg=7.51Âµs   min=1.4Âµs   med=2.9Âµs   max=878Âµs    p(90)=4.67Âµs   p(95)=5.9Âµs
http_req_connecting............: avg=2.19Âµs   min=0s      med=0s      max=291.7Âµs  p(90)=0s       p(95)=0s
http_req_duration..............: avg=99.25ms  min=82.04ms med=97.41ms max=148.97ms p(90)=107.43ms p(95)=111.69ms
  { expected_response:true }...: avg=99.25ms  min=82.04ms med=97.41ms max=148.97ms p(90)=107.43ms p(95)=111.69ms
http_req_failed................: 0.00%   âœ“ 0        âœ— 1344
http_req_receiving.............: avg=145.59Âµs min=33.7Âµs  med=125Âµs   max=1.25ms   p(90)=183.84Âµs p(95)=224.23Âµs
http_req_sending...............: avg=46.12Âµs  min=10.7Âµs  med=49.09Âµs max=194.5Âµs  p(90)=66.27Âµs  p(95)=80.7Âµs
http_req_tls_handshaking.......: avg=0s       min=0s      med=0s      max=0s       p(90)=0s       p(95)=0s
http_req_waiting...............: avg=99.06ms  min=81.89ms med=97.23ms max=148.69ms p(90)=107.22ms p(95)=111.48ms
http_reqs......................: 1344    20.09422/s
iteration_duration.............: avg=1m6s     min=1m6s    med=1m6s    max=1m6s     p(90)=1m6s     p(95)=1m6s
iterations.....................: 2       0.029902/s
vus............................: 2       min=2      max=2
vus_max........................: 2       min=2      max=2
```

**Nginx - PHP FPM** *(17472 requests   277/s)*
```
checks.........................: 100.00% 17472
data_received..................: 24 MB   384 kB/s
data_sent......................: 4.6 MB  74 kB/s
http_req_blocked...............: avg=2.87Âµs   min=1.3Âµs  med=2.4Âµs   max=1.04ms  p(90)=3.6Âµs   p(95)=4.2Âµs
http_req_connecting............: avg=35ns     min=0s     med=0s      max=320Âµs   p(90)=0s      p(95)=0s
http_req_duration..............: avg=6.99ms   min=2.38ms med=6.6ms   max=96.06ms p(90)=7.93ms  p(95)=10.05ms
  { expected_response:true }...: avg=6.99ms   min=2.38ms med=6.6ms   max=96.06ms p(90)=7.93ms  p(95)=10.05ms
http_req_failed................: 0.00%   âœ“ 0          âœ— 17472
http_req_receiving.............: avg=104.91Âµs min=29.1Âµs med=100.8Âµs max=1.58ms  p(90)=139.9Âµs p(95)=157.9Âµs
http_req_sending...............: avg=34.98Âµs  min=7Âµs    med=41.5Âµs  max=2.85ms  p(90)=55.2Âµs  p(95)=61.4Âµs
http_req_tls_handshaking.......: avg=0s       min=0s     med=0s      max=0s      p(90)=0s      p(95)=0s
http_req_waiting...............: avg=6.85ms   min=2.28ms med=6.47ms  max=95.92ms p(90)=7.78ms  p(95)=9.92ms
http_reqs......................: 17472   277.366621/s
iteration_duration.............: avg=4.83s    min=4.74s  med=4.81s   max=5.16s   p(90)=4.92s   p(95)=5.07s
iterations.....................: 26      0.412748/s
vus............................: 2       min=2        max=2
vus_max........................: 2       min=2        max=2
```

:books: https://www.php.net/manual/en/install.fpm.php
📚 https://symfony.com/doc/current/performance.html

### CODE REVIEW

**Comment by youenchene** [comment]
Hi a big thanks for the contribution.

This is almost what we are looking for.

Almost... because remember this project is not a language benchmark competition.

But an eco-benchmark to identify which design choice generate more or less footprint.

php engine and webserver are part of this design choice.

So the target would be to add services and target use case.


For php for the moment we have :

- php-symfony

regarding your PR

we would add : 

- php-symfony-fpm
- php-symfony-fpm-nginx

does a :

- php-symfony-cgi-nginx

make sense?

(never see it in production)

**Comment by Alban-io** [comment]
> But an eco-benchmark to identify which design choice generate more or less footprint.

Performance is directly related with CPU/memory footprint

Currently, the measurements are performed on a  PHP "development" configuration.
With [some modifications while running on Apache2](https://github.com/Boavizta/ecobenchmark-applicationweb-backend/commit/d698b8fb588585b86aae94112d247e139a0ffc40) to get closer to a production configuration

| configuration | http_req_duration | req rate |
|---------------|-------------------|----------|
| current       | 97.41ms           | 20/s     |
| suggest       | 12.42ms           | 150/s    |

___

> make sense?

I suggest : 
- php-symfony-apache2 | _mod_php_ (current code)
- php-symfony-nginx | _PHP FPM_

NGINX - PHP FPM is very often used to run heavy-loaded Symfony app, other web servers also provide FastCGI (Apache2, Caddy, Lighttpd ...)

**Comment by youenchene** [comment]
Ok I suggest 3 services :

- php-symfony-apache2-dev | mod_php (current code) - no optim on apache
- php-symfony-apache2 | mod_php (current code)
- php-symfony-nginx | PHP FPM

Why? Because there is learning for the communities here. The PHP is quite heterogeneous and there so many production working with the default configuration. A message on if you spent 10 mn setting a better configuration can be quite useful.

The the next 3 next days I will write a first version of the CONTRIBUTING.md to help contributers.

**Comment by youenchene** [comment]
Issues :

- https://github.com/Boavizta/ecobenchmark-applicationweb-backend/issues/13
- https://github.com/Boavizta/ecobenchmark-applicationweb-backend/issues/14

**Comment by youenchene** [comment]
Here it is : https://github.com/Boavizta/ecobenchmark-applicationweb-backend/blob/main/CONTRIBUTING.md

**Comment by youenchene** [comment]
@Alban-io quick question (I am creating the 3 uses cases for php based on your contribution)

Can you explain few of your changes :

In [doctrine.yaml](https://github.com/Boavizta/ecobenchmark-applicationweb-backend/pull/11/files#diff-c3eb7c51b3dbd38af59c03141ae44938808602ee1f0bd69ad1e03fa9159ebe97) :
persistent: true

Deletion of [service/php-symfony/config/packages/twig.yaml](https://github.com/Boavizta/ecobenchmark-applicationweb-backend/pull/11/files#diff-fe4c35ca700b68c5f1c9cb9a498e0dd15eb95a570ba80a3fb9dec1bca543ad35)

+ add of Twig Bundle.

In [service/php-symfony/config/services.yaml](https://github.com/Boavizta/ecobenchmark-applicationweb-backend/pull/11/files#diff-52d070d5bb819f9d5f3e887a3d0edf7fbba67eb1c0c1276439d2f6ac380c45fc) :

parameters:
    container.dumper.inline_factories: true
    
 
Why I am asking, it's to have useable design comparison. I need to know if you add this change because of your current best practice or for performance improvement.

**Comment by jgermond** [comment]
> In [doctrine.yaml](https://github.com/Boavizta/ecobenchmark-applicationweb-backend/pull/11/files#diff-c3eb7c51b3dbd38af59c03141ae44938808602ee1f0bd69ad1e03fa9159ebe97) : persistent: true

Doctrine establish a persistent connection. 

> Deletion of [service/php-symfony/config/packages/twig.yaml](https://github.com/Boavizta/ecobenchmark-applicationweb-backend/pull/11/files#diff-fe4c35ca700b68c5f1c9cb9a498e0dd15eb95a570ba80a3fb9dec1bca543ad35)
> 
> * add of Twig Bundle.

Since we have an application with a JSON only API, the twig dependency is useless.

> In [service/php-symfony/config/services.yaml](https://github.com/Boavizta/ecobenchmark-applicationweb-backend/pull/11/files#diff-52d070d5bb819f9d5f3e887a3d0edf7fbba67eb1c0c1276439d2f6ac380c45fc) :
> 
> parameters: container.dumper.inline_factories: true

https://symfony.com/doc/current/performance.html#dump-the-service-container-into-a-single-file:
```
Symfony compiles the [service container](https://symfony.com/doc/current/service_container.html) into multiple small files by default. Set this parameter to true to compile the entire container into a single file, which could improve performance when using "class preloading" in PHP 7.4 or newer versions:
```

**Comment by youenchene** [comment]
Ok :

**php-symfony-apache2-dev** will get 

- [doctrine.yaml](https://github.com/Boavizta/ecobenchmark-applicationweb-backend/pull/11/files#diff-c3eb7c51b3dbd38af59c03141ae44938808602ee1f0bd69ad1e03fa9159ebe97) : persistent: true
- Twig dependencies fix.
- change here https://github.com/Boavizta/ecobenchmark-applicationweb-backend/commit/d698b8fb588585b86aae94112d247e139a0ffc40 (except ocache)


**php-symfony-apache2** will get :

- parameters: container.dumper.inline_factories: true
- ocache

**Comment by jgermond** [comment]
Will **php-symfony-apache2** get the **persisten** and **twig** change too ?

**Comment by youenchene** [comment]
So we show (or not) that spending 5mn to add a few performance paramaters can help.

**Comment by youenchene** [comment]
@Alban-io looks like I have issue on the nginx case

> 2022/09/14 16:09:58 [error] 40#40: *1 FastCGI sent in stderr: "PHP message: [critical] Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred in the driver: could not find driver" at /symfony/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 117" while reading response header from upstream, client: 172.17.0.1, server: localhost, request: "GET /api/stats HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "localhost:8080"

(and we are in pgsql case)

If I add the mysql dependency (make no sense, but anyway) :

2022/09/14 17:37:24 [error] 40#40: *1 FastCGI sent in stderr: "PHP message: [critical] Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory" at /symfony/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 101" while reading response header from upstream, client: 172.17.0.1, server: localhost, request: "GET /api/stats HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "localhost:8080"

Did you test your contributions?

The PR is there : https://github.com/Boavizta/ecobenchmark-applicationweb-backend/pull/23


(note that I have to activate environment variables for both production optimize cases)

**Comment by Alban-io** [comment]
> Did you test your contributions?

Yes, runner run on my PR.

```bash
git clone git@github.com:Alban-io/ecobenchmark-applicationweb-backend.git
cd ecobenchmark-applicationweb-backend/service/php-symfony/
git checkout php-symfony-fpm
docker build -t jdrouet/eco-benchmark:service-php-symfony-default .
docker-compose up
```

```txt
php-symfony-runner-1    |      ✓ login
php-symfony-runner-1    |      ✓ list creation
php-symfony-runner-1    |      ✓ task creation
php-symfony-runner-1    |      ✓ success listing
php-symfony-runner-1    |      ✓ success stats
php-symfony-runner-1    |
php-symfony-runner-1    |      checks.........................: 100.00% ✓ 16128      ✗ 0
php-symfony-runner-1    |      data_received..................: 23 MB   381 kB/s
php-symfony-runner-1    |      data_sent......................: 4.3 MB  71 kB/s
php-symfony-runner-1    |      http_req_blocked...............: avg=2.97µs   min=1.3µs  med=2.5µs   max=1ms     p(90)=3.8µs    p(95)=4.5µs
php-symfony-runner-1    |      http_req_connecting............: avg=39ns     min=0s     med=0s      max=321.1µs p(90)=0s       p(95)=0s
php-symfony-runner-1    |      http_req_duration..............: avg=7.26ms   min=2.65ms med=6.69ms  max=94ms    p(90)=8.22ms   p(95)=10.8ms
php-symfony-runner-1    |        { expected_response:true }...: avg=7.26ms   min=2.65ms med=6.69ms  max=94ms    p(90)=8.22ms   p(95)=10.8ms
php-symfony-runner-1    |      http_req_failed................: 0.00%   ✓ 0          ✗ 16128
php-symfony-runner-1    |      http_req_receiving.............: avg=103.89µs min=28.7µs med=102.4µs max=706.7µs p(90)=141.19µs p(95)=157.9µs
php-symfony-runner-1    |      http_req_sending...............: avg=34.42µs  min=7.3µs  med=30.7µs  max=267.7µs p(90)=56.4µs   p(95)=62.66µs
php-symfony-runner-1    |      http_req_tls_handshaking.......: avg=0s       min=0s     med=0s      max=0s      p(90)=0s       p(95)=0s
php-symfony-runner-1    |      http_req_waiting...............: avg=7.12ms   min=2.55ms med=6.55ms  max=93.81ms p(90)=8.05ms   p(95)=10.64ms
php-symfony-runner-1    |      http_reqs......................: 16128   267.681078/s
php-symfony-runner-1    |      iteration_duration.............: avg=5.01s    min=4.88s  med=5.01s   max=5.15s   p(90)=5.13s    p(95)=5.13s
php-symfony-runner-1    |      iterations.....................: 24      0.398335/s
php-symfony-runner-1    |      vus............................: 2       min=2        max=2
php-symfony-runner-1    |      vus_max........................: 2       min=2        max=2
php-symfony-runner-1    |
php-symfony-runner-1 exited with code 0
```

**Comment by youenchene** [comment]
I meant the docker with the docker run command in the README.md

Le sam. 17 sept. 2022 à 08:28, Alban Baixas ***@***.***> a
écrit :

**Comment by youenchene** [comment]
Solved here : https://github.com/Boavizta/ecobenchmark-applicationweb-backend/pull/23

**Pull request closed without merging**
